[pytest]

pythonpath = .

testpaths = tests

python_files = test_*.py

python_functions = test_*

strict_markers = true


markers = 
    smoke: Critical smoke test
    regression: Regression tests
    negaive: Negative test scenarios